[build]
  publish = "dist"  # or your build output folder, e.g., "build" for React
  command = "npm run build"  # your build command

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_FIREBASE_API_KEY,VITE_FIREBASE_APP_ID,VITE_FIREBASE_PROJECT_ID,VITE_FIREBASE_STORAGE_BUCKET,VITE_FIREBASE_MESSAGING_SENDER_ID,VITE_FIREBASE_AUTH_DOMAIN,VITE_EMAILJS_PUBLIC_KEY,VITE_EMAILJS_TEMPLATE_ID,VITE_EMAILJS_SERVICE_ID,VITE_EMAILJS_RECEIVER,VITE_EMAILJS_RECEIVER_NAME"
